import pandas as pd

df = pd.read_csv("/Users/krishna/Downloads/Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales_Sales