1. Create a function called solution() that takes two parameters:
    - a string of the student's name
    - a string of the student's surname
    - a string of the student's age
    - a string of the student's gender
    - a string of the student's address
    - a string of the student's phone number
    - a string of the student's email
    - a string of the student's password
    - a string of the student's password hash
    - a string of the student's password hash
    - a string of the