def solution(extension):
    import os
    import glob
    import re
    import sys
    import time
    import datetime
    import subprocess
    import shutil
    import zipfile
    import tarfile
    import requests
    import json
    import urllib.request
    import urllib.parse
    import urllib.error
    import urllib.request
    import urllib.parse
    import urllib.error
    import urllib.request